### ISSUE TITLE
JsonDataTable not available?

### ISSUE THREAD

**Issue by martypowell** [AlexanderKrutov/DataTables.Queryable#11]
I searched through the repo and I couldn't find JsonDataTable method. any ideas?

**Comment by AlexanderKrutov** [comment]
@martypowell Hi Marty, `JsonDataTable` is a helper method used to convert  `IPagedList<T>` to ASP.NET-specific `JsonResult` class. It does not included into the `DataTables.Queryable` library because it does not have dependencies from ASP.NET and can be used with any implementation of web server, for example, with Nancy.
So it's a developer-related task to implement own converter from `IPagedList<T>` to Json response.
You can find implementation of the `JsonDataTable` method here:
https://github.com/AlexanderKrutov/DataTables.Queryable/blob/3cd5af9421c541ab96ebb79f7e99dcbc65223c6a/DataTables.Queryable.Samples/Controllers/DataTablesController.cs#L78

**Comment by martypowell** [comment]
@AlexanderKrutov awesome, thanks for the quick response, actually working on implementing my own right now 😄
